apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "1889475594"
          message: |
            {{ if .Alerts.Firing }}🚨 ТРЕВОГА
            {{ range .Alerts.Firing }}{{ .Annotations.summary }}
            {{ end }}{{ end }}{{ if .Alerts.Resolved }}✅ НОРМА
            {{ range .Alerts.Resolved }}{{ .Annotations.summary }}
            {{ end }}{{ end }}
